app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_404:
    path:     /404
    defaults: { _controller: AppBundle:Default:generate404 }

app_artist_index:
    path:     /artists
    defaults: { _controller: AppBundle:Artist:index }

app_artist_show_json:
    path:     /artist/{id}.json
    defaults: { _controller: AppBundle:Artist:showJson }

app_artist_new:
    path:     /artist/new
    defaults: { _controller: AppBundle:Artist:create }

app_artist_update:
    path:     /artist/update/{id}
    defaults: { _controller: AppBundle:Artist:update }

app_artist_show:
    path:     /artist/{id}
    defaults: { _controller: AppBundle:Artist:show }

app_mail_send:
    path: /pumpit
    defaults: { _controller: AppBundle:Mail:send }

app_playlist_index:
    path:     /playlists
    defaults: { _controller: AppBundle:Playlist:index }

app_playlist_show:
    path:     /playlist/{id}
    defaults: { _controller: AppBundle:Playlist:show }

app_security_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

app_track_index:
    path:     /tracks
    defaults: { _controller: AppBundle:Track:index }

app_track_show_json:
    path:     /tracks/{id}.json
    defaults: { _controller: AppBundle:Track:showJson }

app_track_show:
    path:     /track/{id}
    defaults: { _controller: AppBundle:Track:show }

app_track_session_show:
    path:     /tracks/session/show
    defaults: { _controller: AppBundle:Track:sessionShow }

app_track_session:
    path:     /tracks/session/{id}
    defaults: { _controller: AppBundle:Track:session }
